[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format" }
language-servers = [
  { name = "clangd" }
]

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }
language-servers = [
  { name = "clangd" }
]

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server" }
]
